export const types = {
    SEND_REQUEST_LOGIN: 'SEND_REQUEST_LOGIN',
    SEND_REQUEST_LOGIN_SUCCESS: 'SEND_REQUEST_LOGIN_SUCCESS',
    SEND_REQUEST_LOGIN_FAILURE: 'SEND_REQUEST_LOGIN_FAILURE',

    SEND_REQUEST_CHANGE_PASSWORD: 'SEND_REQUEST_CHANGE_PASSWORD',
    SEND_REQUEST_CHANGE_PASSWORD_SUCCESS: 'SEND_REQUEST_CHANGE_PASSWORD_SUCCESS',
    SEND_REQUEST_CHANGE_PASSWORD_FAILURE: 'SEND_REQUEST_CHANGE_PASSWORD_FAILURE',

    GET_REQUEST_CATEGORY: 'GET_REQUEST_CATEGORY',
    GET_REQUEST_CATEGORY_SUCCESS: 'GET_REQUEST_CATEGORY_SUCCESS',
    GET_REQUEST_CATEGORY_FAILURE: 'GET_REQUEST_CATEGORY_FAILURE',

    SEND_REQUEST_ADD_CATEGORY: 'SEND_REQUEST_ADD_CATEGORY',
    SEND_REQUEST_ADD_CATEGORY_SUCCESS: 'SEND_REQUEST_ADD_CATEGORY_SUCCESS',
    SEND_REQUEST_ADD_CATEGORY_FAILURE: 'SEND_REQUEST_ADD_CATEGORY_FAILURE',

    SEND_REQUEST_LOGOUT: 'SEND_REQUEST_LOGOUT',
    SEND_REQUEST_LOGOUT_SUCCESS: 'SEND_REQUEST_LOGOUT_SUCCESS',
    SEND_REQUEST_LOGOUT_FAILURE: 'SEND_REQUEST_LOGOUT_FAILURE',

    SEND_REQUEST_DELETE_CATEGORY: 'SEND_REQUEST_DELETE_CATEGORY',
    SEND_REQUEST_DELETE_CATEGORY_SUCCESS: 'SEND_REQUEST_DELETE_CATEGORY_SUCCESS',
    SEND_REQUEST_DELETE_CATEGORY_FAILURE: 'SEND_REQUEST_DELETE_CATEGORY_FAILURE',

    SEND_REQUEST_UPDATE_CATEGORY: 'SEND_REQUEST_UPDATE_CATEGORY',
    SEND_REQUEST_UPDATE_CATEGORY_SUCCESS: 'SEND_REQUEST_UPDATE_CATEGORY_SUCCESS',
    SEND_REQUEST_UPDATE_CATEGORY_FAILURE: 'SEND_REQUEST_UPDATE_CATEGORY_FAILURE',

    GET_EMPLOYEE_DATA: 'GET_EMPLOYEE_DATA',
    GET_EMPLOYEE_DATA_SUCCESS: 'GET_EMPLOYEE_DATA_SUCCESS',
    GET_EMPLOYEE_DATA_FAILURE: 'GET_EMPLOYEE_DATA_FAILURE',

    SEND_REQUEST_EMP_REG_DATA: 'SEND_REQUEST_EMP_REG_DATA',
    SEND_REQUEST_EMP_REG_DATA_SUCCESS: 'SEND_REQUEST_EMP_REG_DATA_SUCCESS',
    SEND_REQUEST_EMP_REG_DATA_FAILURE: 'SEND_REQUEST_EMP_REG_DATA_FAILURE',

    SEND_LOGIN_RESET: 'SEND_LOGIN_RESET',

    GET_SINGLE_EMPLOYEE_DATA: 'GET_SINGLE_EMPLOYEE_DATA',
    GET_SINGLE_EMPLOYEE_DATA_SUCCESS: 'GET_SINGLE_EMPLOYEE_DATA_SUCCESS',
    GET_SINGLE_EMPLOYEE_DATA_FAILURE: 'GET_SINGLE_EMPLOYEE_DATA_FAILURE',

    SEND_REQUEST_UPDATE_EMPLOYEE: 'SEND_REQUEST_UPDATE_EMPLOYEE',
    SEND_REQUEST_UPDATE_EMPLOYEE_SUCCESS: 'SEND_REQUEST_UPDATE_EMPLOYEE_SUCCESS',
    SEND_REQUEST_UPDATE_EMPLOYEE_FAILURE: 'SEND_REQUEST_UPDATE_EMPLOYEE_FAILURE',
    SEND_EMPLOYEE_RESET: 'SEND_EMPLOYEE_RESET',

    SEND_REQUEST_EMPLOYEE_STATUS: 'SEND_REQUEST_EMPLOYEE_STATUS',
    SEND_REQUEST_EMPLOYEE_STATUS_SUCCESS: 'SEND_REQUEST_EMPLOYEE_STATUS_SUCCESS',
    SEND_REQUEST_EMPLOYEE_STATUS_FAILURE: 'SEND_REQUEST_EMPLOYEE_STATUS_FAILURE',

    SEND_REQUEST_CATEGORY_STATUS: 'SEND_REQUEST_CATEGORY_STATUS',
    SEND_REQUEST_CATEGORY_STATUS_SUCCESS: 'SEND_REQUEST_CATEGORY_STATUS_SUCCESS',
    SEND_REQUEST_CATEGORY_STATUS_FAILURE: 'SEND_REQUEST_CATEGORY_STATUS_FAILURE',

    GET_REQUEST_CATEGORY_STOCK_LIST: 'GET_REQUEST_CATEGORY_STOCK_LIST',
    GET_REQUEST_CATEGORY_STOCK_LIST_SUCCESS: 'GET_REQUEST_CATEGORY_STOCK_LIST_SUCCESS',
    GET_REQUEST_CATEGORY_STOCK_LIST_FAILURE: 'GET_REQUEST_CATEGORY_STOCK_LIST_FAILURE',

    SEND_REQUEST_ADD_PRODUCT:'SEND_REQUEST_ADD_PRODUCT',
    SEND_REQUEST_ADD_PRODUCT_SUCCESS:'SEND_REQUEST_ADD_PRODUCT_SUCCESS',
    SEND_REQUEST_ADD_PRODUCT_FAILURE:'SEND_REQUEST_ADD_PRODUCT_FAILURE',

    GET_PRODUCT_LIST:'GET_PRODUCT_LIST',
    GET_PRODUCT_LIST_SUCCESS:'GET_PRODUCT_LIST_SUCCESS',
    GET_PRODUCT_LIST_FAILURE:'GET_PRODUCT_LIST_FAILURE',

    GET_PRODUCT_DATA:'GET_PRODUCT_DATA',
    GET_PRODUCT_DATA_SUCCESS:'GET_PRODUCT_DATA_SUCCESS',
    GET_PRODUCT_DATA_FAILURE:'GET_PRODUCT_DATA_FAILURE',

    SEND_REQUEST_UPDATE_PRODUCT:'SEND_REQUEST_UPDATE_PRODUCT',
    SEND_REQUEST_UPDATE_PRODUCT_SUCCESS:'SEND_REQUEST_UPDATE_PRODUCT_SUCCESS',
    SEND_REQUEST_UPDATE_PRODUCT_FAILURE:'SEND_REQUEST_UPDATE_PRODUCT_FAILURE',

    SEND_REQUEST_PRODUCT_STATUS:'SEND_REQUEST_PRODUCT_STATUS',
    SEND_REQUEST_PRODUCT_STATUS_SUCCESS:'SEND_REQUEST_PRODUCT_STATUS_SUCCESS',
    SEND_REQUEST_PRODUCT_STATUS_FAILURE:'SEND_REQUEST_PRODUCT_STATUS_FAILURE',

    GET_ALLOCATION_LIST:'GET_ALLOCATION_LIST',
    GET_ALLOCATION_LIST_SUCCESS:'GET_ALLOCATION_LIST_SUCCESS',
    GET_ALLOCATION_LIST_FAILURE:'GET_ALLOCATION_LIST_FAILURE',

    SEND_ALLOCATION_ADD_DATA:'SEND_ALLOCATION_ADD_DATA',
    SEND_ALLOCATION_ADD_DATA_SUCCESS:'SEND_ALLOCATION_ADD_DATA_SUCCESS',
    SEND_ALLOCATION_ADD_DATA_FAILURE:'SEND_ALLOCATION_ADD_DATA_FAILURE',

    SEND_ALLOCATION_STATUS:'SEND_ALLOCATION_STATUS',
    SEND_ALLOCATION_STATUS_SUCCESS:'SEND_ALLOCATION_STATUS_SUCCESS',
    SEND_ALLOCATION_STATUS_FAILURE:'SEND_ALLOCATION_STATUS_FAILURE',

}